# === FUNCTIONALITY SETTINGS ===
POWER_LINE: true # Automatically burns all leftover fuels
DO_NOT_BURN: # If POWER_LINE is true, don't burn these
  - toluene
  - phenol
  - hydrogen
  - creosote oil
  - sulfuric naphtha
  - sulfuric gas
  - sulfuric heavy fuel
  - sulfuric light fuel
  - coal tar oil
  - naphtha
  - creosote oil
  - biomass
  - oil
  - seed oil
  - methane
  - naquadah gas
  - ether
OUTPUT_FORMAT: png # png or pdf (pdf is searchable)
USE_RAINBOW_EDGES: true # feature to help distinguish between overlapping edges
DUR_FORMAT: sec # choose either "ticks" or "sec"
VIEW_ON_COMPLETION: true
KEEP_BACK_EDGES: false

PRINT_BOTTLENECKS: true
USE_BOTTLENECK_EXACT_VOLTAGE: false
BOTTLENECK_MIN_VOLTAGE: IV
MAX_BOTTLENECKS: 5

# === VISUALS ===
GENERAL_FONT: arial  # nodes and edges
SUMMARY_FONT: arial
GROUP_FONT: verdana
NODE_FONTSIZE: 11
EDGE_FONTSIZE: 10
GROUP_FONTSIZE: 18
BACKGROUND_COLOR: '#043742'
EDGECOLOR_CYCLE:
  - '#b58900' # 'yellow'
  - '#cb4b16' # 'orange'
  - '#dc322f' # 'red'
  - '#d33682' # 'magenta'
  - '#6c71c4' # 'violet'
  - '#268bd2' # 'blue'
  - '#2aa198' # 'cyan'
  - '#859900' # 'green'
SOURCESINK_COLOR: 'ghostwhite'
NONLOCKEDNODE_COLOR: 'lightblue2'
LOCKEDNODE_COLOR: 'green'
POSITIVE_COLOR: '#859900'
NEGATIVE_COLOR: '#dc322f'
RECYCLABLE_COLOR: '#2aa198'
# Find color codes at: https://graphviz.org/doc/info/colors.html
# Trying to pick one similar to the color of multis, but
# there are some exceptions like
# LPF machines and mixer share the same multi-use casings
DEFAULT_MACHINE_COLOR: aliceblue
MACHINE_COLORS:
  electric blast furnace: lightgreen
  volcanus: lightgreen
  chemical reactor: dimgrey
  large chemical reactor: dimgrey
  distillery: lightblue1
  distillation tower: lightblue1
  dangote: lightblue1
  centrifuge: goldenrod2
  industrial centrifuge: goldenrod2
  electrolyzer: lightsalmon2
  industrial electrolyzer: lightsalmon2
  autoclave: slateblue3
  vacuum freezer: royalblue1
  cryogenic freezer: royalblue1
  ore washing plant: teal
  macerator: peru
  maceration stack: peru
  industrial dehydrator: tomato3
  dehydrator: tomato3
  alloy blast smelter: wheat3
  industrial sledgehammer: seagreen4
  forge hammer: seagreen4

ORIENTATION: 'TB'
# TB: Vertical, LR: Horizontal, BT: Vertical Inverted, RL: Horizontal Inverted
# [TB, LR, BT, RL]

LINE_STYLE: 'spline'
# [line, spline, polyline, curved]

RANKSEP: '1.25'
NODESEP: '0.25'
# Node separation size in X/Y.
# This is a suggestion, the graphing algorithm will ignore numbers that are too small.

COMBINE_INPUTS: true
COMBINE_OUTPUTS: true
# Whether to (visually) create a new meta node before multi-input/after multi-output ports


# { You should probably only modify these if you are dev
DEBUG_SHOW_EVERY_STEP: false
SHOW_MACHINE_INDICES: false
STRIP_BRACKETS: true
STREAMHANDLER_LEVEL: INFO
LOG_ADJACENCY_LIST: false
# }
